# Generated by Django 6.0.6 on 2026-06-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
