# Generated by Django 6.0.6 on 2026-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_business_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits_remaining',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits_total',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=10),
        ),
    ]
