# Generated by Django 6.0.6 on 2026-10-05 13:23

from decimal import Decimal

from django.db import migrations, models


def backfill_topup_credits(apps, schema_editor):
    """Seed topup_credits from approved top-up payments, capped at the current balance."""
    from users.packs import TOPUP_PACKS

    User = apps.get_model("users", "User")
    Payment = apps.get_model("admin_panel", "Payment")
    bought = {}
    for user_id, pack in Payment.objects.filter(status="paid", payment_type="topup").values_list("user_id", "pack"):
        credits = TOPUP_PACKS.get(pack, {}).get("credits", Decimal("0"))
        bought[user_id] = bought.get(user_id, Decimal("0")) + credits
    for user in User.objects.filter(pk__in=bought):
        user.topup_credits = min(bought[user.pk], user.credits_remaining)
        user.save(update_fields=["topup_credits"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verified'),
        ('admin_panel', '0006_payment_pack_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topup_credits',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_topup_credits, migrations.RunPython.noop),
    ]
