# Generated by Django 6.0.6 on 2026-06-26 19:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, default='', max_length=16)),
                ('color', models.CharField(blank=True, default='#2563eb', max_length=7)),
                ('org', models.CharField(blank=True, default='', max_length=120)),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('brand_industry', models.CharField(blank=True, default='', max_length=100)),
                ('brand_color_hex', models.CharField(blank=True, default='#2563eb', max_length=7)),
                ('brand_logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='projects.project')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-last_accessed_at'], name='projects_pr_owner_i_4b6fdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('project', 'platform')},
        ),
    ]
