# Generated by Django 6.0.6 on 2026-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
