# Generated by Django 6.0.6 on 2026-09-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_publishjob_adaccount_adboostjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='provider',
            field=models.CharField(choices=[('meta', 'Meta'), ('tiktok', 'TikTok'), ('snap', 'Snapchat'), ('google', 'Google Ads')], max_length=20),
        ),
    ]
