# Generated by Django 6.0.6 on 2026-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_publishjob_draft_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': [models.OrderBy(models.F('last_accessed_at'), descending=True, nulls_last=True), '-created_at']},
        ),
    ]
