# Generated by Django 6.0.6 on 2026-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_ordering_nulls_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
