# Generated by Django 6.1 on 2026-09-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_seed_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payments/screenshots/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='creditadjustment',
            name='reason',
            field=models.CharField(choices=[('plan_change', 'Plan change'), ('grant', 'Manual grant'), ('reset', 'Manual reset'), ('adjust', 'Adjustment'), ('payment', 'Payment approval')], default='grant', max_length=20),
        ),
    ]
