# Generated by Django 6.1 on 2026-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_payment_plan_payment_reviewed_at_payment_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pack',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('topup', 'Top-up')], default='subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditadjustment',
            name='reason',
            field=models.CharField(choices=[('plan_change', 'Plan change'), ('grant', 'Manual grant'), ('reset', 'Manual reset'), ('adjust', 'Adjustment'), ('payment', 'Payment approval'), ('topup', 'Top-up')], default='grant', max_length=20),
        ),
    ]
