# Generated by Django 6.0.6 on 2026-10-05 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_plan_usage_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('credits', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_pkr', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('popular', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
