# Generated by Django 6.0.6 on 2026-10-06 11:17

import shutil
from pathlib import Path

import admin_panel.models
from django.conf import settings
from django.db import migrations, models


def move_proofs_private(apps, schema_editor):
    """Move existing payment proofs out of the public MEDIA_ROOT (same relative names)."""
    public = Path(settings.MEDIA_ROOT) / "payments"
    private = Path(settings.PRIVATE_MEDIA_ROOT) / "payments"
    if not public.is_dir():
        return
    for src in [p for p in public.rglob("*") if p.is_file()]:
        dest = private / src.relative_to(public)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dest))
    shutil.rmtree(public, ignore_errors=True)


def move_proofs_public(apps, schema_editor):
    public = Path(settings.MEDIA_ROOT) / "payments"
    private = Path(settings.PRIVATE_MEDIA_ROOT) / "payments"
    if not private.is_dir():
        return
    for src in [p for p in private.rglob("*") if p.is_file()]:
        dest = public / src.relative_to(private)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dest))


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_seed_topup_packs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.FileField(blank=True, null=True, storage=admin_panel.models.private_storage, upload_to='payments/screenshots/%Y/%m/'),
        ),
        migrations.RunPython(move_proofs_private, move_proofs_public),
    ]
