# Generated by Django 6.0.6 on 2026-07-18 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_socialaccount_external_id_socialaccount_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects/%Y/%m/%d/uploads/')),
                ('content_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('textToImage', 'Text to image'), ('edit', 'Edit'), ('multiEdit', 'Multi-image edit'), ('upscale', 'Upscale'), ('removeBackground', 'Remove background')], max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('mask_image', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('credits_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credits_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('fal_request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='content_ima_project_519602_idx'), models.Index(fields=['status'], name='content_ima_status_9f7349_idx')],
            },
        ),
    ]
