# Generated by Django 6.0.6 on 2026-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejob',
            name='fal_response_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='fal_status_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
