# Generated by Django 6.0.6 on 2026-07-19 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_imagejob_fal_response_url_imagejob_fal_status_url'),
        ('projects', '0002_socialaccount_external_id_socialaccount_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('generating', 'Generating'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('thumbnail_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('source_url', models.CharField(blank=True, default='', max_length=2000)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('capability', models.CharField(blank=True, max_length=32, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('source_index', models.PositiveSmallIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_assets', to='content.imagejob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_assets', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='content_lib_project_b2b65f_idx'), models.Index(fields=['project', 'media_type', '-created_at'], name='content_lib_project_75477c_idx'), models.Index(fields=['project', 'deleted_at'], name='content_lib_project_ebfbe5_idx')],
                'constraints': [models.UniqueConstraint(fields=('image_job', 'source_index'), name='uniq_library_asset_job_index')],
            },
        ),
    ]
