# Generated by Django 6.0.6 on 2026-07-19 12:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_library_asset'),
        ('projects', '0002_socialaccount_external_id_socialaccount_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('textToVideo', 'Text to video'), ('imageToVideo', 'Image to video'), ('firstLastFrame', 'First to last frame')], max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('video', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('credits_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credits_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('fal_request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('fal_status_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('fal_response_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='libraryasset',
            name='video_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_assets', to='content.videojob'),
        ),
        migrations.AddConstraint(
            model_name='libraryasset',
            constraint=models.UniqueConstraint(fields=('video_job', 'source_index'), name='uniq_library_asset_video_job_index'),
        ),
        migrations.AddIndex(
            model_name='videojob',
            index=models.Index(fields=['project', '-created_at'], name='content_vid_project_b54dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='videojob',
            index=models.Index(fields=['status'], name='content_vid_status_c49dd2_idx'),
        ),
    ]
