# Generated by Django 6.0.6 on 2026-08-10 17:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_decimal_credit_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('ad', 'Ad'), ('reel', 'Reel'), ('carousel', 'Carousel'), ('story', 'Story'), ('product', 'Product'), ('announce', 'Announcement')], max_length=24)),
                ('format', models.CharField(max_length=40)),
                ('is_video', models.BooleanField(default=False)),
                ('preview_url', models.CharField(blank=True, default='', max_length=2000)),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('uses_last_7d', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uses_last_7d', '-uses_count', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'category', '-uses_last_7d'], name='content_tem_is_acti_649261_idx'), models.Index(fields=['is_active', '-created_at'], name='content_tem_is_acti_3819b6_idx'), models.Index(fields=['is_video'], name='content_tem_is_vide_70b2d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateUseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_events', to='content.template')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_use_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', '-created_at'], name='content_tem_templat_d1fc5a_idx'), models.Index(fields=['user', '-created_at'], name='content_tem_user_id_9de542_idx')],
            },
        ),
    ]
