# Generated by Django 6.0.6 on 2026-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_template_templateuseevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejob',
            name='fal_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='videojob',
            name='fal_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
