# Generated by Django 6.1 on 2026-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_favoritetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('ads-product', 'Ads & Product'), ('brand-logo', 'Brand & Logo'), ('video', 'Video'), ('illustration-3d', 'Illustration & 3D'), ('posters-visuals', 'Posters & Visuals'), ('portraits', 'Portraits'), ('storyboard-characters', 'Storyboard & Characters'), ('wallpaper', 'Wallpaper')], help_text='Gallery section this template belongs to (meigen category slugs).', max_length=32),
        ),
    ]
