# Generated by Django 6.0.6 on 2026-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejob',
            name='topup_credits_reserved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='videojob',
            name='topup_credits_reserved',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
